name: e2e Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: ${{github.workspace}}/gin-mongo

    steps:
    - name: Test-Report
      uses: alphasians/test-reportql@main
      with:
        working-directory: ${{env.GITHUB_WORKSPACE}}
        delay: 20
