name: e2e Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gin-mongo

    steps:
    - name: Test-Report
      uses: alphasians/test-reportql@main
      env:
        working-directory: ${{env.working-directory}}
        delay: 20
